//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dhss.Assist.WorkerWeb.Web.Intake.ApplicationEntry.Technical {
    
    
    public partial class TechnicalQuestions {
        
        /// <summary>
        /// dsTechnical_HouseholdGeneralInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dhss.Framework.Web.UserControls.DataServiceLinqDataSource dsTechnical_HouseholdGeneralInfo;
        
        /// <summary>
        /// hdIsPageChange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdIsPageChange;
        
        /// <summary>
        /// fvdsTechnical_HouseholdGeneralInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView fvdsTechnical_HouseholdGeneralInfo;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Dhss.Assist.WorkerWeb.Web.Intake.ApplicationEntry.ApplicationEntryLayout Master {
            get {
                return ((Dhss.Assist.WorkerWeb.Web.Intake.ApplicationEntry.ApplicationEntryLayout)(base.Master));
            }
        }
    }
}
