
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dhss.Assist.WorkerWeb.Repository.ApplicationEntry.Technical
{
    using System;
    using System.Linq;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Services.Client;
    using System.Data.Services.Common;
    using Dhss.Assist.WorkerWeb.Repository;
    using Dhss.Assist.WorkerWeb.ServicesFramework;
    using Dhss.Assist.WorkerWeb.Entity.ApplicationEntry.Technical;
    
    public partial class TechnicalContext_OdataRepository : DataServiceRepositoryBase
    {
    	public TechnicalContext_OdataRepository() : base("TechnicalContext_OdataRepository")
    	{
    		//Init repositories
    		_Technical_Address = new Lazy<DataServiceQuery<Technical_Address>>(() => CreateQuery<Technical_Address>("Technical_Address"));
    		_Technical_BenefitCapInfo = new Lazy<DataServiceQuery<Technical_BenefitCapInfo>>(() => CreateQuery<Technical_BenefitCapInfo>("Technical_BenefitCapInfo"));
    		_Technical_BreastAndCervicalCancer = new Lazy<DataServiceQuery<Technical_BreastAndCervicalCancer>>(() => CreateQuery<Technical_BreastAndCervicalCancer>("Technical_BreastAndCervicalCancer"));
    		_Technical_ContinuouslyEligibleNewborn = new Lazy<DataServiceQuery<Technical_ContinuouslyEligibleNewborn>>(() => CreateQuery<Technical_ContinuouslyEligibleNewborn>("Technical_ContinuouslyEligibleNewborn"));
    		_Technical_CRDPInfo = new Lazy<DataServiceQuery<Technical_CRDPInfo>>(() => CreateQuery<Technical_CRDPInfo>("Technical_CRDPInfo"));
    		_Technical_Disability = new Lazy<DataServiceQuery<Technical_Disability>>(() => CreateQuery<Technical_Disability>("Technical_Disability"));
    		_Technical_FosterCare = new Lazy<DataServiceQuery<Technical_FosterCare>>(() => CreateQuery<Technical_FosterCare>("Technical_FosterCare"));
    		_Technical_HomeCommunityBasedService = new Lazy<DataServiceQuery<Technical_HomeCommunityBasedService>>(() => CreateQuery<Technical_HomeCommunityBasedService>("Technical_HomeCommunityBasedService"));
    		_Technical_IndividualBenefits = new Lazy<DataServiceQuery<Technical_IndividualBenefits>>(() => CreateQuery<Technical_IndividualBenefits>("Technical_IndividualBenefits"));
    		_Technical_InstitutionInfo = new Lazy<DataServiceQuery<Technical_InstitutionInfo>>(() => CreateQuery<Technical_InstitutionInfo>("Technical_InstitutionInfo"));
    		_Technical_PersonDemographics = new Lazy<DataServiceQuery<Technical_PersonDemographics>>(() => CreateQuery<Technical_PersonDemographics>("Technical_PersonDemographics"));
    		_Technical_PersonRefugee = new Lazy<DataServiceQuery<Technical_PersonRefugee>>(() => CreateQuery<Technical_PersonRefugee>("Technical_PersonRefugee"));
    		_Technical_Phone = new Lazy<DataServiceQuery<Technical_Phone>>(() => CreateQuery<Technical_Phone>("Technical_Phone"));
    		_Technical_Pregnancy = new Lazy<DataServiceQuery<Technical_Pregnancy>>(() => CreateQuery<Technical_Pregnancy>("Technical_Pregnancy"));
    		_Technical_ProtectedSSI = new Lazy<DataServiceQuery<Technical_ProtectedSSI>>(() => CreateQuery<Technical_ProtectedSSI>("Technical_ProtectedSSI"));
    		_Technical_SchoolEnrollment = new Lazy<DataServiceQuery<Technical_SchoolEnrollment>>(() => CreateQuery<Technical_SchoolEnrollment>("Technical_SchoolEnrollment"));
    		_Technical_Sponsor = new Lazy<DataServiceQuery<Technical_Sponsor>>(() => CreateQuery<Technical_Sponsor>("Technical_Sponsor"));
    		_Technical_SponsorOrganization = new Lazy<DataServiceQuery<Technical_SponsorOrganization>>(() => CreateQuery<Technical_SponsorOrganization>("Technical_SponsorOrganization"));
    		_Technical_SpousalImpoverishment = new Lazy<DataServiceQuery<Technical_SpousalImpoverishment>>(() => CreateQuery<Technical_SpousalImpoverishment>("Technical_SpousalImpoverishment"));
    		_Technical_TeenParentExemption = new Lazy<DataServiceQuery<Technical_TeenParentExemption>>(() => CreateQuery<Technical_TeenParentExemption>("Technical_TeenParentExemption"));
    		_Technical_Application = new Lazy<DataServiceQuery<Technical_Application>>(() => CreateQuery<Technical_Application>("Technical_Application"));
    		_Technical_ApplicationEntity = new Lazy<DataServiceQuery<Technical_ApplicationEntity>>(() => CreateQuery<Technical_ApplicationEntity>("Technical_ApplicationEntity"));
    		_Technical_Case = new Lazy<DataServiceQuery<Technical_Case>>(() => CreateQuery<Technical_Case>("Technical_Case"));
    		_Technical_CashProgram = new Lazy<DataServiceQuery<Technical_CashProgram>>(() => CreateQuery<Technical_CashProgram>("Technical_CashProgram"));
    		_Technical_ChildCareAdditionalDemographics = new Lazy<DataServiceQuery<Technical_ChildCareAdditionalDemographics>>(() => CreateQuery<Technical_ChildCareAdditionalDemographics>("Technical_ChildCareAdditionalDemographics"));
    		_Technical_ChildCareProgram = new Lazy<DataServiceQuery<Technical_ChildCareProgram>>(() => CreateQuery<Technical_ChildCareProgram>("Technical_ChildCareProgram"));
    		_Technical_DisabledChildrenProgram = new Lazy<DataServiceQuery<Technical_DisabledChildrenProgram>>(() => CreateQuery<Technical_DisabledChildrenProgram>("Technical_DisabledChildrenProgram"));
    		_Technical_FoodBenefitsProgram = new Lazy<DataServiceQuery<Technical_FoodBenefitsProgram>>(() => CreateQuery<Technical_FoodBenefitsProgram>("Technical_FoodBenefitsProgram"));
    		_Techincal_MedicalAssistanceProgram = new Lazy<DataServiceQuery<Techincal_MedicalAssistanceProgram>>(() => CreateQuery<Techincal_MedicalAssistanceProgram>("Techincal_MedicalAssistanceProgram"));
    		_Technical_PersonRelation = new Lazy<DataServiceQuery<Technical_PersonRelation>>(() => CreateQuery<Technical_PersonRelation>("Technical_PersonRelation"));
    		_Technical_ProgramDetail = new Lazy<DataServiceQuery<Technical_ProgramDetail>>(() => CreateQuery<Technical_ProgramDetail>("Technical_ProgramDetail"));
    		_Technical_QualifiedMemberBeneficiaryProgram = new Lazy<DataServiceQuery<Technical_QualifiedMemberBeneficiaryProgram>>(() => CreateQuery<Technical_QualifiedMemberBeneficiaryProgram>("Technical_QualifiedMemberBeneficiaryProgram"));
    		_Technical_Entity = new Lazy<DataServiceQuery<Technical_Entity>>(() => CreateQuery<Technical_Entity>("Technical_Entity"));
    		_Technical_PersonAdditionalAttributes = new Lazy<DataServiceQuery<Technical_PersonAdditionalAttributes>>(() => CreateQuery<Technical_PersonAdditionalAttributes>("Technical_PersonAdditionalAttributes"));
    		_Technical_Race = new Lazy<DataServiceQuery<Technical_Race>>(() => CreateQuery<Technical_Race>("Technical_Race"));
    		_Technical_LivingArrangement = new Lazy<DataServiceQuery<Technical_LivingArrangement>>(() => CreateQuery<Technical_LivingArrangement>("Technical_LivingArrangement"));
    		_Technical_HouseholdGeneralInfo = new Lazy<DataServiceQuery<Technical_HouseholdGeneralInfo>>(() => CreateQuery<Technical_HouseholdGeneralInfo>("Technical_HouseholdGeneralInfo"));
    		_Technical_HealthInsuranceLoss = new Lazy<DataServiceQuery<Technical_HealthInsuranceLoss>>(() => CreateQuery<Technical_HealthInsuranceLoss>("Technical_HealthInsuranceLoss"));
    		_Technical_DisasterBenefitInfo = new Lazy<DataServiceQuery<Technical_DisasterBenefitInfo>>(() => CreateQuery<Technical_DisasterBenefitInfo>("Technical_DisasterBenefitInfo"));
    		_Technical_TaxDependency = new Lazy<DataServiceQuery<Technical_TaxDependency>>(() => CreateQuery<Technical_TaxDependency>("Technical_TaxDependency"));
    		_Technical_TaxDependencyDetails = new Lazy<DataServiceQuery<Technical_TaxDependencyDetails>>(() => CreateQuery<Technical_TaxDependencyDetails>("Technical_TaxDependencyDetails"));
    		_Technical_PrimaryPerson = new Lazy<DataServiceQuery<Technical_PrimaryPerson>>(() => CreateQuery<Technical_PrimaryPerson>("Technical_PrimaryPerson"));
    		_Technical_AdditionalCashProgram = new Lazy<DataServiceQuery<Technical_AdditionalCashProgram>>(() => CreateQuery<Technical_AdditionalCashProgram>("Technical_AdditionalCashProgram"));
    		_Technical_AdditionalChildCareProgram = new Lazy<DataServiceQuery<Technical_AdditionalChildCareProgram>>(() => CreateQuery<Technical_AdditionalChildCareProgram>("Technical_AdditionalChildCareProgram"));
    		_Technical_AdditionalDisabledChildrenProgram = new Lazy<DataServiceQuery<Technical_AdditionalDisabledChildrenProgram>>(() => CreateQuery<Technical_AdditionalDisabledChildrenProgram>("Technical_AdditionalDisabledChildrenProgram"));
    		_Technical_AdditionalFoodBenefitsProgram = new Lazy<DataServiceQuery<Technical_AdditionalFoodBenefitsProgram>>(() => CreateQuery<Technical_AdditionalFoodBenefitsProgram>("Technical_AdditionalFoodBenefitsProgram"));
    		_Technical_AdditionalMedicalAssistanceProgram = new Lazy<DataServiceQuery<Technical_AdditionalMedicalAssistanceProgram>>(() => CreateQuery<Technical_AdditionalMedicalAssistanceProgram>("Technical_AdditionalMedicalAssistanceProgram"));
    		_Technical_AdditionalQMBProgram = new Lazy<DataServiceQuery<Technical_AdditionalQMBProgram>>(() => CreateQuery<Technical_AdditionalQMBProgram>("Technical_AdditionalQMBProgram"));
    		_Technical_VLPLookUp = new Lazy<DataServiceQuery<Technical_VLPLookUp>>(() => CreateQuery<Technical_VLPLookUp>("Technical_VLPLookUp"));
    		_Technical_EmailAddress = new Lazy<DataServiceQuery<Technical_EmailAddress>>(() => CreateQuery<Technical_EmailAddress>("Technical_EmailAddress"));
    		_Technical_ViewCaseInformationHouseholdSummary = new Lazy<DataServiceQuery<Technical_ViewCaseInformationHouseholdSummary>>(() => CreateQuery<Technical_ViewCaseInformationHouseholdSummary>("Technical_ViewCaseInformationHouseholdSummary"));
            //_Technical_Worker = new Lazy<DataServiceQuery<Technical_Worker>>(() => CreateQuery<Technical_Worker>("Technical_Worker"));
            _Technical_PoolDetails = new Lazy<DataServiceQuery<Technical_PoolDetails>>(() => CreateQuery<Technical_PoolDetails>("Technical_PoolDetails"));
    		_Technical_CaseAssistanceGroup = new Lazy<DataServiceQuery<Technical_CaseAssistanceGroup>>(() => CreateQuery<Technical_CaseAssistanceGroup>("Technical_CaseAssistanceGroup"));
    		_Technical_Eligibility = new Lazy<DataServiceQuery<Technical_Eligibility>>(() => CreateQuery<Technical_Eligibility>("Technical_Eligibility"));
    		_Technical_IndividualEligibility = new Lazy<DataServiceQuery<Technical_IndividualEligibility>>(() => CreateQuery<Technical_IndividualEligibility>("Technical_IndividualEligibility"));
    		_Technical_PersonProfile = new Lazy<DataServiceQuery<Technical_PersonProfile>>(() => CreateQuery<Technical_PersonProfile>("Technical_PersonProfile"));
    		_Technical_CaseEligibilityProfile = new Lazy<DataServiceQuery<Technical_CaseEligibilityProfile>>(() => CreateQuery<Technical_CaseEligibilityProfile>("Technical_CaseEligibilityProfile"));
    		_Technical_CaseDriverFlow = new Lazy<DataServiceQuery<Technical_CaseDriverFlow>>(() => CreateQuery<Technical_CaseDriverFlow>("Technical_CaseDriverFlow"));
    		_Technical_CaseLocationInfo = new Lazy<DataServiceQuery<Technical_CaseLocationInfo>>(() => CreateQuery<Technical_CaseLocationInfo>("Technical_CaseLocationInfo"));
    		_Technical_DX_LIS_ApplicationDetails = new Lazy<DataServiceQuery<Technical_DX_LIS_ApplicationDetails>>(() => CreateQuery<Technical_DX_LIS_ApplicationDetails>("Technical_DX_LIS_ApplicationDetails"));
    		_Technical_DX_SDX_ApplicationDetails = new Lazy<DataServiceQuery<Technical_DX_SDX_ApplicationDetails>>(() => CreateQuery<Technical_DX_SDX_ApplicationDetails>("Technical_DX_SDX_ApplicationDetails"));
    		_Technical_Income = new Lazy<DataServiceQuery<Technical_Income>>(() => CreateQuery<Technical_Income>("Technical_Income"));
    		_Technical_UnearnedIncome = new Lazy<DataServiceQuery<Technical_UnearnedIncome>>(() => CreateQuery<Technical_UnearnedIncome>("Technical_UnearnedIncome"));
    		_Technical_UnearnedIncomeDetail = new Lazy<DataServiceQuery<Technical_UnearnedIncomeDetail>>(() => CreateQuery<Technical_UnearnedIncomeDetail>("Technical_UnearnedIncomeDetail"));
    		_Technical_CaseLoadWorker = new Lazy<DataServiceQuery<Technical_CaseLoadWorker>>(() => CreateQuery<Technical_CaseLoadWorker>("Technical_CaseLoadWorker"));
    		_CaseInformationHouseholdSummary_ARMS_V = new Lazy<DataServiceQuery<CaseInformationHouseholdSummary_ARMS_V>>(() => CreateQuery<CaseInformationHouseholdSummary_ARMS_V>("CaseInformationHouseholdSummary_ARMS_V"));
    		_Technical_ASSISTMain = new Lazy<DataServiceQuery<Technical_ASSISTMain>>(() => CreateQuery<Technical_ASSISTMain>("Technical_ASSISTMain"));
    		_Technical_IncarcerationDetails = new Lazy<DataServiceQuery<Technical_IncarcerationDetails>>(() => CreateQuery<Technical_IncarcerationDetails>("Technical_IncarcerationDetails"));
    		_Technical_CommunityEngagement = new Lazy<DataServiceQuery<Technical_CommunityEngagement>>(() => CreateQuery<Technical_CommunityEngagement>("Technical_CommunityEngagement"));
    		_Technical_CommunityEngagementHardshipWaiver = new Lazy<DataServiceQuery<Technical_CommunityEngagementHardshipWaiver>>(() => CreateQuery<Technical_CommunityEngagementHardshipWaiver>("Technical_CommunityEngagementHardshipWaiver"));
    		_Technical_CommunityEngagementMedicalDetails = new Lazy<DataServiceQuery<Technical_CommunityEngagementMedicalDetails>>(() => CreateQuery<Technical_CommunityEngagementMedicalDetails>("Technical_CommunityEngagementMedicalDetails"));
    		_Technical_CommunityEngagementSummary = new Lazy<DataServiceQuery<Technical_CommunityEngagementSummary>>(() => CreateQuery<Technical_CommunityEngagementSummary>("Technical_CommunityEngagementSummary"));
    		_Technical_VolunteeringWorkProgram = new Lazy<DataServiceQuery<Technical_VolunteeringWorkProgram>>(() => CreateQuery<Technical_VolunteeringWorkProgram>("Technical_VolunteeringWorkProgram"));
    		_Technical_VolunteeringWorkProgramDetails = new Lazy<DataServiceQuery<Technical_VolunteeringWorkProgramDetails>>(() => CreateQuery<Technical_VolunteeringWorkProgramDetails>("Technical_VolunteeringWorkProgramDetails"));
    	}
    
    	//Declare repositories  
    	private readonly Lazy<DataServiceQuery<Technical_Address>> _Technical_Address;
    	public DataServiceQuery<Technical_Address> Technical_Address {get {return _Technical_Address.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_BenefitCapInfo>> _Technical_BenefitCapInfo;
    	public DataServiceQuery<Technical_BenefitCapInfo> Technical_BenefitCapInfo {get {return _Technical_BenefitCapInfo.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_BreastAndCervicalCancer>> _Technical_BreastAndCervicalCancer;
    	public DataServiceQuery<Technical_BreastAndCervicalCancer> Technical_BreastAndCervicalCancer {get {return _Technical_BreastAndCervicalCancer.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_ContinuouslyEligibleNewborn>> _Technical_ContinuouslyEligibleNewborn;
    	public DataServiceQuery<Technical_ContinuouslyEligibleNewborn> Technical_ContinuouslyEligibleNewborn {get {return _Technical_ContinuouslyEligibleNewborn.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CRDPInfo>> _Technical_CRDPInfo;
    	public DataServiceQuery<Technical_CRDPInfo> Technical_CRDPInfo {get {return _Technical_CRDPInfo.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Disability>> _Technical_Disability;
    	public DataServiceQuery<Technical_Disability> Technical_Disability {get {return _Technical_Disability.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_FosterCare>> _Technical_FosterCare;
    	public DataServiceQuery<Technical_FosterCare> Technical_FosterCare {get {return _Technical_FosterCare.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_HomeCommunityBasedService>> _Technical_HomeCommunityBasedService;
    	public DataServiceQuery<Technical_HomeCommunityBasedService> Technical_HomeCommunityBasedService {get {return _Technical_HomeCommunityBasedService.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_IndividualBenefits>> _Technical_IndividualBenefits;
    	public DataServiceQuery<Technical_IndividualBenefits> Technical_IndividualBenefits {get {return _Technical_IndividualBenefits.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_InstitutionInfo>> _Technical_InstitutionInfo;
    	public DataServiceQuery<Technical_InstitutionInfo> Technical_InstitutionInfo {get {return _Technical_InstitutionInfo.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_PersonDemographics>> _Technical_PersonDemographics;
    	public DataServiceQuery<Technical_PersonDemographics> Technical_PersonDemographics {get {return _Technical_PersonDemographics.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_PersonRefugee>> _Technical_PersonRefugee;
    	public DataServiceQuery<Technical_PersonRefugee> Technical_PersonRefugee {get {return _Technical_PersonRefugee.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Phone>> _Technical_Phone;
    	public DataServiceQuery<Technical_Phone> Technical_Phone {get {return _Technical_Phone.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Pregnancy>> _Technical_Pregnancy;
    	public DataServiceQuery<Technical_Pregnancy> Technical_Pregnancy {get {return _Technical_Pregnancy.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_ProtectedSSI>> _Technical_ProtectedSSI;
    	public DataServiceQuery<Technical_ProtectedSSI> Technical_ProtectedSSI {get {return _Technical_ProtectedSSI.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_SchoolEnrollment>> _Technical_SchoolEnrollment;
    	public DataServiceQuery<Technical_SchoolEnrollment> Technical_SchoolEnrollment {get {return _Technical_SchoolEnrollment.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Sponsor>> _Technical_Sponsor;
    	public DataServiceQuery<Technical_Sponsor> Technical_Sponsor {get {return _Technical_Sponsor.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_SponsorOrganization>> _Technical_SponsorOrganization;
    	public DataServiceQuery<Technical_SponsorOrganization> Technical_SponsorOrganization {get {return _Technical_SponsorOrganization.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_SpousalImpoverishment>> _Technical_SpousalImpoverishment;
    	public DataServiceQuery<Technical_SpousalImpoverishment> Technical_SpousalImpoverishment {get {return _Technical_SpousalImpoverishment.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_TeenParentExemption>> _Technical_TeenParentExemption;
    	public DataServiceQuery<Technical_TeenParentExemption> Technical_TeenParentExemption {get {return _Technical_TeenParentExemption.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Application>> _Technical_Application;
    	public DataServiceQuery<Technical_Application> Technical_Application {get {return _Technical_Application.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_ApplicationEntity>> _Technical_ApplicationEntity;
    	public DataServiceQuery<Technical_ApplicationEntity> Technical_ApplicationEntity {get {return _Technical_ApplicationEntity.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Case>> _Technical_Case;
    	public DataServiceQuery<Technical_Case> Technical_Case {get {return _Technical_Case.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CashProgram>> _Technical_CashProgram;
    	public DataServiceQuery<Technical_CashProgram> Technical_CashProgram {get {return _Technical_CashProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_ChildCareAdditionalDemographics>> _Technical_ChildCareAdditionalDemographics;
    	public DataServiceQuery<Technical_ChildCareAdditionalDemographics> Technical_ChildCareAdditionalDemographics {get {return _Technical_ChildCareAdditionalDemographics.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_ChildCareProgram>> _Technical_ChildCareProgram;
    	public DataServiceQuery<Technical_ChildCareProgram> Technical_ChildCareProgram {get {return _Technical_ChildCareProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_DisabledChildrenProgram>> _Technical_DisabledChildrenProgram;
    	public DataServiceQuery<Technical_DisabledChildrenProgram> Technical_DisabledChildrenProgram {get {return _Technical_DisabledChildrenProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_FoodBenefitsProgram>> _Technical_FoodBenefitsProgram;
    	public DataServiceQuery<Technical_FoodBenefitsProgram> Technical_FoodBenefitsProgram {get {return _Technical_FoodBenefitsProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Techincal_MedicalAssistanceProgram>> _Techincal_MedicalAssistanceProgram;
    	public DataServiceQuery<Techincal_MedicalAssistanceProgram> Techincal_MedicalAssistanceProgram {get {return _Techincal_MedicalAssistanceProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_PersonRelation>> _Technical_PersonRelation;
    	public DataServiceQuery<Technical_PersonRelation> Technical_PersonRelation {get {return _Technical_PersonRelation.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_ProgramDetail>> _Technical_ProgramDetail;
    	public DataServiceQuery<Technical_ProgramDetail> Technical_ProgramDetail {get {return _Technical_ProgramDetail.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_QualifiedMemberBeneficiaryProgram>> _Technical_QualifiedMemberBeneficiaryProgram;
    	public DataServiceQuery<Technical_QualifiedMemberBeneficiaryProgram> Technical_QualifiedMemberBeneficiaryProgram {get {return _Technical_QualifiedMemberBeneficiaryProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Entity>> _Technical_Entity;
    	public DataServiceQuery<Technical_Entity> Technical_Entity {get {return _Technical_Entity.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_PersonAdditionalAttributes>> _Technical_PersonAdditionalAttributes;
    	public DataServiceQuery<Technical_PersonAdditionalAttributes> Technical_PersonAdditionalAttributes {get {return _Technical_PersonAdditionalAttributes.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Race>> _Technical_Race;
    	public DataServiceQuery<Technical_Race> Technical_Race {get {return _Technical_Race.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_LivingArrangement>> _Technical_LivingArrangement;
    	public DataServiceQuery<Technical_LivingArrangement> Technical_LivingArrangement {get {return _Technical_LivingArrangement.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_HouseholdGeneralInfo>> _Technical_HouseholdGeneralInfo;
    	public DataServiceQuery<Technical_HouseholdGeneralInfo> Technical_HouseholdGeneralInfo {get {return _Technical_HouseholdGeneralInfo.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_HealthInsuranceLoss>> _Technical_HealthInsuranceLoss;
    	public DataServiceQuery<Technical_HealthInsuranceLoss> Technical_HealthInsuranceLoss {get {return _Technical_HealthInsuranceLoss.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_DisasterBenefitInfo>> _Technical_DisasterBenefitInfo;
    	public DataServiceQuery<Technical_DisasterBenefitInfo> Technical_DisasterBenefitInfo {get {return _Technical_DisasterBenefitInfo.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_TaxDependency>> _Technical_TaxDependency;
    	public DataServiceQuery<Technical_TaxDependency> Technical_TaxDependency {get {return _Technical_TaxDependency.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_TaxDependencyDetails>> _Technical_TaxDependencyDetails;
    	public DataServiceQuery<Technical_TaxDependencyDetails> Technical_TaxDependencyDetails {get {return _Technical_TaxDependencyDetails.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_PrimaryPerson>> _Technical_PrimaryPerson;
    	public DataServiceQuery<Technical_PrimaryPerson> Technical_PrimaryPerson {get {return _Technical_PrimaryPerson.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_AdditionalCashProgram>> _Technical_AdditionalCashProgram;
    	public DataServiceQuery<Technical_AdditionalCashProgram> Technical_AdditionalCashProgram {get {return _Technical_AdditionalCashProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_AdditionalChildCareProgram>> _Technical_AdditionalChildCareProgram;
    	public DataServiceQuery<Technical_AdditionalChildCareProgram> Technical_AdditionalChildCareProgram {get {return _Technical_AdditionalChildCareProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_AdditionalDisabledChildrenProgram>> _Technical_AdditionalDisabledChildrenProgram;
    	public DataServiceQuery<Technical_AdditionalDisabledChildrenProgram> Technical_AdditionalDisabledChildrenProgram {get {return _Technical_AdditionalDisabledChildrenProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_AdditionalFoodBenefitsProgram>> _Technical_AdditionalFoodBenefitsProgram;
    	public DataServiceQuery<Technical_AdditionalFoodBenefitsProgram> Technical_AdditionalFoodBenefitsProgram {get {return _Technical_AdditionalFoodBenefitsProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_AdditionalMedicalAssistanceProgram>> _Technical_AdditionalMedicalAssistanceProgram;
    	public DataServiceQuery<Technical_AdditionalMedicalAssistanceProgram> Technical_AdditionalMedicalAssistanceProgram {get {return _Technical_AdditionalMedicalAssistanceProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_AdditionalQMBProgram>> _Technical_AdditionalQMBProgram;
    	public DataServiceQuery<Technical_AdditionalQMBProgram> Technical_AdditionalQMBProgram {get {return _Technical_AdditionalQMBProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_VLPLookUp>> _Technical_VLPLookUp;
    	public DataServiceQuery<Technical_VLPLookUp> Technical_VLPLookUp {get {return _Technical_VLPLookUp.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_EmailAddress>> _Technical_EmailAddress;
    	public DataServiceQuery<Technical_EmailAddress> Technical_EmailAddress {get {return _Technical_EmailAddress.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_ViewCaseInformationHouseholdSummary>> _Technical_ViewCaseInformationHouseholdSummary;
    	public DataServiceQuery<Technical_ViewCaseInformationHouseholdSummary> Technical_ViewCaseInformationHouseholdSummary {get {return _Technical_ViewCaseInformationHouseholdSummary.Value;}}
        //private readonly Lazy<DataServiceQuery<Technical_Worker>> _Technical_Worker;
        //public DataServiceQuery<Technical_Worker> Technical_Worker {get {return _Technical_Worker.Value;}}
        private readonly Lazy<DataServiceQuery<Technical_PoolDetails>> _Technical_PoolDetails;
    	public DataServiceQuery<Technical_PoolDetails> Technical_PoolDetails {get {return _Technical_PoolDetails.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CaseAssistanceGroup>> _Technical_CaseAssistanceGroup;
    	public DataServiceQuery<Technical_CaseAssistanceGroup> Technical_CaseAssistanceGroup {get {return _Technical_CaseAssistanceGroup.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Eligibility>> _Technical_Eligibility;
    	public DataServiceQuery<Technical_Eligibility> Technical_Eligibility {get {return _Technical_Eligibility.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_IndividualEligibility>> _Technical_IndividualEligibility;
    	public DataServiceQuery<Technical_IndividualEligibility> Technical_IndividualEligibility {get {return _Technical_IndividualEligibility.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_PersonProfile>> _Technical_PersonProfile;
    	public DataServiceQuery<Technical_PersonProfile> Technical_PersonProfile {get {return _Technical_PersonProfile.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CaseEligibilityProfile>> _Technical_CaseEligibilityProfile;
    	public DataServiceQuery<Technical_CaseEligibilityProfile> Technical_CaseEligibilityProfile {get {return _Technical_CaseEligibilityProfile.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CaseDriverFlow>> _Technical_CaseDriverFlow;
    	public DataServiceQuery<Technical_CaseDriverFlow> Technical_CaseDriverFlow {get {return _Technical_CaseDriverFlow.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CaseLocationInfo>> _Technical_CaseLocationInfo;
    	public DataServiceQuery<Technical_CaseLocationInfo> Technical_CaseLocationInfo {get {return _Technical_CaseLocationInfo.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_DX_LIS_ApplicationDetails>> _Technical_DX_LIS_ApplicationDetails;
    	public DataServiceQuery<Technical_DX_LIS_ApplicationDetails> Technical_DX_LIS_ApplicationDetails {get {return _Technical_DX_LIS_ApplicationDetails.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_DX_SDX_ApplicationDetails>> _Technical_DX_SDX_ApplicationDetails;
    	public DataServiceQuery<Technical_DX_SDX_ApplicationDetails> Technical_DX_SDX_ApplicationDetails {get {return _Technical_DX_SDX_ApplicationDetails.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_Income>> _Technical_Income;
    	public DataServiceQuery<Technical_Income> Technical_Income {get {return _Technical_Income.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_UnearnedIncome>> _Technical_UnearnedIncome;
    	public DataServiceQuery<Technical_UnearnedIncome> Technical_UnearnedIncome {get {return _Technical_UnearnedIncome.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_UnearnedIncomeDetail>> _Technical_UnearnedIncomeDetail;
    	public DataServiceQuery<Technical_UnearnedIncomeDetail> Technical_UnearnedIncomeDetail {get {return _Technical_UnearnedIncomeDetail.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CaseLoadWorker>> _Technical_CaseLoadWorker;
    	public DataServiceQuery<Technical_CaseLoadWorker> Technical_CaseLoadWorker {get {return _Technical_CaseLoadWorker.Value;}}
    	private readonly Lazy<DataServiceQuery<CaseInformationHouseholdSummary_ARMS_V>> _CaseInformationHouseholdSummary_ARMS_V;
    	public DataServiceQuery<CaseInformationHouseholdSummary_ARMS_V> CaseInformationHouseholdSummary_ARMS_V {get {return _CaseInformationHouseholdSummary_ARMS_V.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_ASSISTMain>> _Technical_ASSISTMain;
    	public DataServiceQuery<Technical_ASSISTMain> Technical_ASSISTMain {get {return _Technical_ASSISTMain.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_IncarcerationDetails>> _Technical_IncarcerationDetails;
    	public DataServiceQuery<Technical_IncarcerationDetails> Technical_IncarcerationDetails {get {return _Technical_IncarcerationDetails.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CommunityEngagement>> _Technical_CommunityEngagement;
    	public DataServiceQuery<Technical_CommunityEngagement> Technical_CommunityEngagement {get {return _Technical_CommunityEngagement.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CommunityEngagementHardshipWaiver>> _Technical_CommunityEngagementHardshipWaiver;
    	public DataServiceQuery<Technical_CommunityEngagementHardshipWaiver> Technical_CommunityEngagementHardshipWaiver {get {return _Technical_CommunityEngagementHardshipWaiver.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CommunityEngagementMedicalDetails>> _Technical_CommunityEngagementMedicalDetails;
    	public DataServiceQuery<Technical_CommunityEngagementMedicalDetails> Technical_CommunityEngagementMedicalDetails {get {return _Technical_CommunityEngagementMedicalDetails.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_CommunityEngagementSummary>> _Technical_CommunityEngagementSummary;
    	public DataServiceQuery<Technical_CommunityEngagementSummary> Technical_CommunityEngagementSummary {get {return _Technical_CommunityEngagementSummary.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_VolunteeringWorkProgram>> _Technical_VolunteeringWorkProgram;
    	public DataServiceQuery<Technical_VolunteeringWorkProgram> Technical_VolunteeringWorkProgram {get {return _Technical_VolunteeringWorkProgram.Value;}}
    	private readonly Lazy<DataServiceQuery<Technical_VolunteeringWorkProgramDetails>> _Technical_VolunteeringWorkProgramDetails;
    	public DataServiceQuery<Technical_VolunteeringWorkProgramDetails> Technical_VolunteeringWorkProgramDetails {get {return _Technical_VolunteeringWorkProgramDetails.Value;}}
    	//Declare AddTo Methods
    	public void AddToTechnical_Address(Technical_Address technical_Address){ AddObject("Technical_Address", technical_Address); }
    	public void AddToTechnical_BenefitCapInfo(Technical_BenefitCapInfo technical_BenefitCapInfo){ AddObject("Technical_BenefitCapInfo", technical_BenefitCapInfo); }
    	public void AddToTechnical_BreastAndCervicalCancer(Technical_BreastAndCervicalCancer technical_BreastAndCervicalCancer){ AddObject("Technical_BreastAndCervicalCancer", technical_BreastAndCervicalCancer); }
    	public void AddToTechnical_ContinuouslyEligibleNewborn(Technical_ContinuouslyEligibleNewborn technical_ContinuouslyEligibleNewborn){ AddObject("Technical_ContinuouslyEligibleNewborn", technical_ContinuouslyEligibleNewborn); }
    	public void AddToTechnical_CRDPInfo(Technical_CRDPInfo technical_CRDPInfo){ AddObject("Technical_CRDPInfo", technical_CRDPInfo); }
    	public void AddToTechnical_Disability(Technical_Disability technical_Disability){ AddObject("Technical_Disability", technical_Disability); }
    	public void AddToTechnical_FosterCare(Technical_FosterCare technical_FosterCare){ AddObject("Technical_FosterCare", technical_FosterCare); }
    	public void AddToTechnical_HomeCommunityBasedService(Technical_HomeCommunityBasedService technical_HomeCommunityBasedService){ AddObject("Technical_HomeCommunityBasedService", technical_HomeCommunityBasedService); }
    	public void AddToTechnical_IndividualBenefits(Technical_IndividualBenefits technical_IndividualBenefits){ AddObject("Technical_IndividualBenefits", technical_IndividualBenefits); }
    	public void AddToTechnical_InstitutionInfo(Technical_InstitutionInfo technical_InstitutionInfo){ AddObject("Technical_InstitutionInfo", technical_InstitutionInfo); }
    	public void AddToTechnical_PersonDemographics(Technical_PersonDemographics technical_PersonDemographics){ AddObject("Technical_PersonDemographics", technical_PersonDemographics); }
    	public void AddToTechnical_PersonRefugee(Technical_PersonRefugee technical_PersonRefugee){ AddObject("Technical_PersonRefugee", technical_PersonRefugee); }
    	public void AddToTechnical_Phone(Technical_Phone technical_Phone){ AddObject("Technical_Phone", technical_Phone); }
    	public void AddToTechnical_Pregnancy(Technical_Pregnancy technical_Pregnancy){ AddObject("Technical_Pregnancy", technical_Pregnancy); }
    	public void AddToTechnical_ProtectedSSI(Technical_ProtectedSSI technical_ProtectedSSI){ AddObject("Technical_ProtectedSSI", technical_ProtectedSSI); }
    	public void AddToTechnical_SchoolEnrollment(Technical_SchoolEnrollment technical_SchoolEnrollment){ AddObject("Technical_SchoolEnrollment", technical_SchoolEnrollment); }
    	public void AddToTechnical_Sponsor(Technical_Sponsor technical_Sponsor){ AddObject("Technical_Sponsor", technical_Sponsor); }
    	public void AddToTechnical_SponsorOrganization(Technical_SponsorOrganization technical_SponsorOrganization){ AddObject("Technical_SponsorOrganization", technical_SponsorOrganization); }
    	public void AddToTechnical_SpousalImpoverishment(Technical_SpousalImpoverishment technical_SpousalImpoverishment){ AddObject("Technical_SpousalImpoverishment", technical_SpousalImpoverishment); }
    	public void AddToTechnical_TeenParentExemption(Technical_TeenParentExemption technical_TeenParentExemption){ AddObject("Technical_TeenParentExemption", technical_TeenParentExemption); }
    	public void AddToTechnical_Application(Technical_Application technical_Application){ AddObject("Technical_Application", technical_Application); }
    	public void AddToTechnical_ApplicationEntity(Technical_ApplicationEntity technical_ApplicationEntity){ AddObject("Technical_ApplicationEntity", technical_ApplicationEntity); }
    	public void AddToTechnical_Case(Technical_Case technical_Case){ AddObject("Technical_Case", technical_Case); }
    	public void AddToTechnical_CashProgram(Technical_CashProgram technical_CashProgram){ AddObject("Technical_CashProgram", technical_CashProgram); }
    	public void AddToTechnical_ChildCareAdditionalDemographics(Technical_ChildCareAdditionalDemographics technical_ChildCareAdditionalDemographics){ AddObject("Technical_ChildCareAdditionalDemographics", technical_ChildCareAdditionalDemographics); }
    	public void AddToTechnical_ChildCareProgram(Technical_ChildCareProgram technical_ChildCareProgram){ AddObject("Technical_ChildCareProgram", technical_ChildCareProgram); }
    	public void AddToTechnical_DisabledChildrenProgram(Technical_DisabledChildrenProgram technical_DisabledChildrenProgram){ AddObject("Technical_DisabledChildrenProgram", technical_DisabledChildrenProgram); }
    	public void AddToTechnical_FoodBenefitsProgram(Technical_FoodBenefitsProgram technical_FoodBenefitsProgram){ AddObject("Technical_FoodBenefitsProgram", technical_FoodBenefitsProgram); }
    	public void AddToTechincal_MedicalAssistanceProgram(Techincal_MedicalAssistanceProgram techincal_MedicalAssistanceProgram){ AddObject("Techincal_MedicalAssistanceProgram", techincal_MedicalAssistanceProgram); }
    	public void AddToTechnical_PersonRelation(Technical_PersonRelation technical_PersonRelation){ AddObject("Technical_PersonRelation", technical_PersonRelation); }
    	public void AddToTechnical_ProgramDetail(Technical_ProgramDetail technical_ProgramDetail){ AddObject("Technical_ProgramDetail", technical_ProgramDetail); }
    	public void AddToTechnical_QualifiedMemberBeneficiaryProgram(Technical_QualifiedMemberBeneficiaryProgram technical_QualifiedMemberBeneficiaryProgram){ AddObject("Technical_QualifiedMemberBeneficiaryProgram", technical_QualifiedMemberBeneficiaryProgram); }
    	public void AddToTechnical_Entity(Technical_Entity technical_Entity){ AddObject("Technical_Entity", technical_Entity); }
    	public void AddToTechnical_PersonAdditionalAttributes(Technical_PersonAdditionalAttributes technical_PersonAdditionalAttributes){ AddObject("Technical_PersonAdditionalAttributes", technical_PersonAdditionalAttributes); }
    	public void AddToTechnical_Race(Technical_Race technical_Race){ AddObject("Technical_Race", technical_Race); }
    	public void AddToTechnical_LivingArrangement(Technical_LivingArrangement technical_LivingArrangement){ AddObject("Technical_LivingArrangement", technical_LivingArrangement); }
    	public void AddToTechnical_HouseholdGeneralInfo(Technical_HouseholdGeneralInfo technical_HouseholdGeneralInfo){ AddObject("Technical_HouseholdGeneralInfo", technical_HouseholdGeneralInfo); }
    	public void AddToTechnical_HealthInsuranceLoss(Technical_HealthInsuranceLoss technical_HealthInsuranceLoss){ AddObject("Technical_HealthInsuranceLoss", technical_HealthInsuranceLoss); }
    	public void AddToTechnical_DisasterBenefitInfo(Technical_DisasterBenefitInfo technical_DisasterBenefitInfo){ AddObject("Technical_DisasterBenefitInfo", technical_DisasterBenefitInfo); }
    	public void AddToTechnical_TaxDependency(Technical_TaxDependency technical_TaxDependency){ AddObject("Technical_TaxDependency", technical_TaxDependency); }
    	public void AddToTechnical_TaxDependencyDetails(Technical_TaxDependencyDetails technical_TaxDependencyDetails){ AddObject("Technical_TaxDependencyDetails", technical_TaxDependencyDetails); }
    	public void AddToTechnical_PrimaryPerson(Technical_PrimaryPerson technical_PrimaryPerson){ AddObject("Technical_PrimaryPerson", technical_PrimaryPerson); }
    	public void AddToTechnical_AdditionalCashProgram(Technical_AdditionalCashProgram technical_AdditionalCashProgram){ AddObject("Technical_AdditionalCashProgram", technical_AdditionalCashProgram); }
    	public void AddToTechnical_AdditionalChildCareProgram(Technical_AdditionalChildCareProgram technical_AdditionalChildCareProgram){ AddObject("Technical_AdditionalChildCareProgram", technical_AdditionalChildCareProgram); }
    	public void AddToTechnical_AdditionalDisabledChildrenProgram(Technical_AdditionalDisabledChildrenProgram technical_AdditionalDisabledChildrenProgram){ AddObject("Technical_AdditionalDisabledChildrenProgram", technical_AdditionalDisabledChildrenProgram); }
    	public void AddToTechnical_AdditionalFoodBenefitsProgram(Technical_AdditionalFoodBenefitsProgram technical_AdditionalFoodBenefitsProgram){ AddObject("Technical_AdditionalFoodBenefitsProgram", technical_AdditionalFoodBenefitsProgram); }
    	public void AddToTechnical_AdditionalMedicalAssistanceProgram(Technical_AdditionalMedicalAssistanceProgram technical_AdditionalMedicalAssistanceProgram){ AddObject("Technical_AdditionalMedicalAssistanceProgram", technical_AdditionalMedicalAssistanceProgram); }
    	public void AddToTechnical_AdditionalQMBProgram(Technical_AdditionalQMBProgram technical_AdditionalQMBProgram){ AddObject("Technical_AdditionalQMBProgram", technical_AdditionalQMBProgram); }
    	public void AddToTechnical_VLPLookUp(Technical_VLPLookUp technical_VLPLookUp){ AddObject("Technical_VLPLookUp", technical_VLPLookUp); }
    	public void AddToTechnical_EmailAddress(Technical_EmailAddress technical_EmailAddress){ AddObject("Technical_EmailAddress", technical_EmailAddress); }
    	public void AddToTechnical_ViewCaseInformationHouseholdSummary(Technical_ViewCaseInformationHouseholdSummary technical_ViewCaseInformationHouseholdSummary){ AddObject("Technical_ViewCaseInformationHouseholdSummary", technical_ViewCaseInformationHouseholdSummary); }
        //public void AddToTechnical_Worker(Technical_Worker technical_Worker){ AddObject("Technical_Worker", technical_Worker); }
        public void AddToTechnical_PoolDetails(Technical_PoolDetails technical_PoolDetails){ AddObject("Technical_PoolDetails", technical_PoolDetails); }
    	public void AddToTechnical_CaseAssistanceGroup(Technical_CaseAssistanceGroup technical_CaseAssistanceGroup){ AddObject("Technical_CaseAssistanceGroup", technical_CaseAssistanceGroup); }
    	public void AddToTechnical_Eligibility(Technical_Eligibility technical_Eligibility){ AddObject("Technical_Eligibility", technical_Eligibility); }
    	public void AddToTechnical_IndividualEligibility(Technical_IndividualEligibility technical_IndividualEligibility){ AddObject("Technical_IndividualEligibility", technical_IndividualEligibility); }
    	public void AddToTechnical_PersonProfile(Technical_PersonProfile technical_PersonProfile){ AddObject("Technical_PersonProfile", technical_PersonProfile); }
    	public void AddToTechnical_CaseEligibilityProfile(Technical_CaseEligibilityProfile technical_CaseEligibilityProfile){ AddObject("Technical_CaseEligibilityProfile", technical_CaseEligibilityProfile); }
    	public void AddToTechnical_CaseDriverFlow(Technical_CaseDriverFlow technical_CaseDriverFlow){ AddObject("Technical_CaseDriverFlow", technical_CaseDriverFlow); }
    	public void AddToTechnical_CaseLocationInfo(Technical_CaseLocationInfo technical_CaseLocationInfo){ AddObject("Technical_CaseLocationInfo", technical_CaseLocationInfo); }
    	public void AddToTechnical_DX_LIS_ApplicationDetails(Technical_DX_LIS_ApplicationDetails technical_DX_LIS_ApplicationDetails){ AddObject("Technical_DX_LIS_ApplicationDetails", technical_DX_LIS_ApplicationDetails); }
    	public void AddToTechnical_DX_SDX_ApplicationDetails(Technical_DX_SDX_ApplicationDetails technical_DX_SDX_ApplicationDetails){ AddObject("Technical_DX_SDX_ApplicationDetails", technical_DX_SDX_ApplicationDetails); }
    	public void AddToTechnical_Income(Technical_Income technical_Income){ AddObject("Technical_Income", technical_Income); }
    	public void AddToTechnical_UnearnedIncome(Technical_UnearnedIncome technical_UnearnedIncome){ AddObject("Technical_UnearnedIncome", technical_UnearnedIncome); }
    	public void AddToTechnical_UnearnedIncomeDetail(Technical_UnearnedIncomeDetail technical_UnearnedIncomeDetail){ AddObject("Technical_UnearnedIncomeDetail", technical_UnearnedIncomeDetail); }
    	public void AddToTechnical_CaseLoadWorker(Technical_CaseLoadWorker technical_CaseLoadWorker){ AddObject("Technical_CaseLoadWorker", technical_CaseLoadWorker); }
    	public void AddToCaseInformationHouseholdSummary_ARMS_V(CaseInformationHouseholdSummary_ARMS_V caseInformationHouseholdSummary_ARMS_V){ AddObject("CaseInformationHouseholdSummary_ARMS_V", caseInformationHouseholdSummary_ARMS_V); }
    	public void AddToTechnical_ASSISTMain(Technical_ASSISTMain technical_ASSISTMain){ AddObject("Technical_ASSISTMain", technical_ASSISTMain); }
    	public void AddToTechnical_IncarcerationDetails(Technical_IncarcerationDetails technical_IncarcerationDetails){ AddObject("Technical_IncarcerationDetails", technical_IncarcerationDetails); }
    	public void AddToTechnical_CommunityEngagement(Technical_CommunityEngagement technical_CommunityEngagement){ AddObject("Technical_CommunityEngagement", technical_CommunityEngagement); }
    	public void AddToTechnical_CommunityEngagementHardshipWaiver(Technical_CommunityEngagementHardshipWaiver technical_CommunityEngagementHardshipWaiver){ AddObject("Technical_CommunityEngagementHardshipWaiver", technical_CommunityEngagementHardshipWaiver); }
    	public void AddToTechnical_CommunityEngagementMedicalDetails(Technical_CommunityEngagementMedicalDetails technical_CommunityEngagementMedicalDetails){ AddObject("Technical_CommunityEngagementMedicalDetails", technical_CommunityEngagementMedicalDetails); }
    	public void AddToTechnical_CommunityEngagementSummary(Technical_CommunityEngagementSummary technical_CommunityEngagementSummary){ AddObject("Technical_CommunityEngagementSummary", technical_CommunityEngagementSummary); }
    	public void AddToTechnical_VolunteeringWorkProgram(Technical_VolunteeringWorkProgram technical_VolunteeringWorkProgram){ AddObject("Technical_VolunteeringWorkProgram", technical_VolunteeringWorkProgram); }
    	public void AddToTechnical_VolunteeringWorkProgramDetails(Technical_VolunteeringWorkProgramDetails technical_VolunteeringWorkProgramDetails){ AddObject("Technical_VolunteeringWorkProgramDetails", technical_VolunteeringWorkProgramDetails); }
    }
    
}

